<?php
declare(strict_types=1);
namespace App\Domain\Generations;
use App\Domain\DomainEvent;
final class Generation {
    /** @var DomainEvent[] */ private array $events = [];
    private function __construct(private GenerationId $id, private string $userId, private string $type, private string $subject, private string $topic, private string $details, private string $grade, private int $duration, private string $lang, private string $prompt, private string $status, private ?string $resultMd, private ?string $resultJson, private \DateTimeImmutable $createdAt, private \DateTimeImmutable $updatedAt) {}
    public static function create(GenerationId $id, string $userId, string $type, string $subject, string $topic, string $details, string $grade, int $duration, string $lang, string $prompt): self { $now = new \DateTimeImmutable('now', new \DateTimeZone('UTC')); $s = new self($id,$userId,$type,$subject,$topic,$details,$grade,$duration,$lang,$prompt,'created',null,null,$now,$now); $s->events[] = new GenerationCreated($id,$now); return $s; }
    public static function reconstitute(GenerationId $id, string $userId, string $type, string $subject, string $topic, string $details, string $grade, int $duration, string $lang, string $prompt, string $status, ?string $resultMd, ?string $resultJson, \DateTimeImmutable $createdAt, \DateTimeImmutable $updatedAt): self { return new self($id,$userId,$type,$subject,$topic,$details,$grade,$duration,$lang,$prompt,$status,$resultMd,$resultJson,$createdAt,$updatedAt); }
    public function update(?string $status, ?string $resultMd, ?string $resultJson, ?string $topic = null, ?string $details = null): void { if ($status !== null) { $this->status=$status; } if ($resultMd !== null) { $this->resultMd=$resultMd; } if ($resultJson !== null) { $this->resultJson=$resultJson; } if ($topic !== null) { $this->topic=$topic; } if ($details !== null) { $this->details=$details; } $this->updatedAt = new \DateTimeImmutable('now', new \DateTimeZone('UTC')); $this->events[] = new GenerationUpdated($this->id, $this->updatedAt); }
    public function id(): GenerationId { return $this->id; } public function userId(): string { return $this->userId; } public function type(): string { return $this->type; } public function subject(): string { return $this->subject; } public function topic(): string { return $this->topic; } public function details(): string { return $this->details; } public function grade(): string { return $this->grade; } public function duration(): int { return $this->duration; } public function lang(): string { return $this->lang; } public function prompt(): string { return $this->prompt; } public function status(): string { return $this->status; } public function resultMd(): ?string { return $this->resultMd; } public function resultJson(): ?string { return $this->resultJson; } public function createdAt(): \DateTimeImmutable { return $this->createdAt; } public function updatedAt(): \DateTimeImmutable { return $this->updatedAt; }
    /** @return DomainEvent[] */ public function releaseDomainEvents(): array { $e=$this->events; $this->events=[]; return $e; }
}
