import React from "react";
import { useNavigate } from "react-router-dom";
import { School, Mail } from "lucide-react";
import StaticPage, { Section, Bullets } from "../components/StaticPage";
import PlansComparison from "../components/PlansComparison";
import { CONTACT_EMAIL } from "../siteConfig";

const T = {
  RU: {
    title: "Тарифы",
    subtitle: "Один тариф. Бесплатный. Ниже — что в него входит и где границы.",
    planName: "Бесплатный",
    price: "0 ₸",
    period: "в месяц",
    planNote: "Без карты. Без пробного периода, который заканчивается.",
    cta: "Начать бесплатно",
    ctaAuthed: "Перейти в хаб",
    included: [
      "Планы уроков без ограничения по количеству",
      "AI-тесты с кодом доступа для класса",
      "Итог урока и AI-отчёт по классу",
      "Классы и списки учеников",
      "Вордл и игры для урока",
      "Экспорт в DOCX",
      "Три языка интерфейса и генерации: RU, KZ, EN",
    ],
    limitsTitle: "Честно о границах",
    limits: [
      "Скорость генерации ограничена квотой AI-провайдера. В час пик запрос может выполняться дольше или попросить повторить попытку.",
      "Сервис работает в браузере, офлайн-режима нет.",
      "Материалы генерирует языковая модель — их нужно проверять перед уроком.",
      "Мы можем ограничить нагрузку от одного аккаунта, если она мешает другим учителям.",
    ],
    whyTitle: "Почему бесплатно",
    whyBody: "Сервис на ранней стадии, и нам важнее, чтобы им пользовались реальные учителя и присылали замечания, чем собрать выручку. Если появится платный тариф, бесплатный уровень останется, а действующие пользователи узнают об изменениях заранее.",
    schoolTitle: "Для школ и методобъединений",
    schoolBody: "Нужны аккаунты для всей школы, единый доступ для методиста или обучение коллектива? Напишите — договоримся, это тоже бесплатно.",
    schoolCta: "Написать нам",
    payTitle: "Что со сменой условий",
    payBody: "Изменения тарифов вступают в силу не раньше чем через 30 дней после уведомления. Контент, созданный до изменений, остаётся доступным и выгружаемым.",
  },
  KZ: {
    title: "Тарифтер",
    subtitle: "Бір тариф. Тегін. Төменде — не кіретіні және шектеулері.",
    planName: "Тегін",
    price: "0 ₸",
    period: "айына",
    planNote: "Картасыз. Аяқталатын сынақ мерзімі жоқ.",
    cta: "Тегін бастау",
    ctaAuthed: "Хабқа өту",
    included: [
      "Сабақ жоспарлары — саны шектелмейді",
      "Сынып үшін код арқылы кіретін AI тесттер",
      "Сабақ қорытындысы және сынып бойынша AI есеп",
      "Сыныптар мен оқушылар тізімі",
      "Вордл және сабаққа арналған ойындар",
      "DOCX экспорты",
      "Үш тіл: RU, KZ, EN",
    ],
    limitsTitle: "Шектеулер туралы шынымен",
    limits: [
      "Генерация жылдамдығы AI провайдерінің квотасымен шектелген. Жүктеме көп кезде сұраныс ұзағырақ орындалуы немесе қайталауды сұрауы мүмкін.",
      "Сервис браузерде жұмыс істейді, офлайн режим жоқ.",
      "Материалдарды тілдік модель жасайды — сабақ алдында тексеру қажет.",
      "Бір аккаунттың жүктемесі басқа мұғалімдерге кедергі келтірсе, оны шектей аламыз.",
    ],
    whyTitle: "Неге тегін",
    whyBody: "Сервис ерте кезеңде, бізге табыс жинағаннан гөрі оны нақты мұғалімдер пайдаланып, ескертулерін жіберуі маңызды. Ақылы тариф пайда болса, тегін деңгей қалады, ал қолданыстағы пайдаланушылар өзгерістер туралы алдын ала біледі.",
    schoolTitle: "Мектептер мен әдістемелік бірлестіктерге",
    schoolBody: "Бүкіл мектепке аккаунт, әдіскерге ортақ қолжетімділік немесе ұжымды оқыту керек пе? Жазыңыз — келісеміз, бұл да тегін.",
    schoolCta: "Бізге жазу",
    payTitle: "Шарттар өзгерсе",
    payBody: "Тариф өзгерістері хабарламадан кейін 30 күннен ерте күшіне енбейді. Өзгерістерге дейін жасалған мазмұн қолжетімді болып қалады және жүктеп алуға болады.",
  },
  EN: {
    title: "Pricing",
    subtitle: "One plan. Free. Here's what's in it and where the limits are.",
    planName: "Free",
    price: "0 ₸",
    period: "per month",
    planNote: "No card. No trial that runs out.",
    cta: "Start for free",
    ctaAuthed: "Go to hub",
    included: [
      "Unlimited lesson plans",
      "AI quizzes with an access code for the class",
      "Lesson summary and AI class report",
      "Classes and student rosters",
      "Wordle and in-lesson games",
      "DOCX export",
      "Three languages for UI and generation: RU, KZ, EN",
    ],
    limitsTitle: "Honest about the limits",
    limits: [
      "Generation speed is bounded by the AI provider's quota. At peak times a request may take longer or ask you to retry.",
      "The service runs in the browser; there is no offline mode.",
      "Materials are generated by a language model and need checking before the lesson.",
      "We may throttle a single account if its load affects other teachers.",
    ],
    whyTitle: "Why it's free",
    whyBody: "The service is early, and real teachers using it and sending feedback matters more to us right now than revenue. If a paid plan appears, the free tier stays and existing users will hear about changes in advance.",
    schoolTitle: "For schools and departments",
    schoolBody: "Need accounts for a whole school, shared access for a head of department, or training for your staff? Email us — we'll sort it out, also free.",
    schoolCta: "Email us",
    payTitle: "If terms change",
    payBody: "Pricing changes take effect no sooner than 30 days after notice. Content created before a change stays accessible and exportable.",
  },
};

export default function PricingPage({ lang = "RU", user, setIsAuthOpen, setAuthMode, resetAuthFields, ...rest }) {
  const t = T[lang] || T.RU;
  const navigate = useNavigate();

  const handleCta = () => {
    if (user) { navigate("/hub"); return; }
    resetAuthFields?.();
    setAuthMode?.("signup");
    setIsAuthOpen?.(true);
  };

  return (
    <StaticPage
      lang={lang}
      user={user}
      isLanding={!user}
      setIsAuthOpen={setIsAuthOpen}
      setAuthMode={setAuthMode}
      resetAuthFields={resetAuthFields}
      {...rest}
      title={t.title}
      subtitle={t.subtitle}
    >
      {/* Одна и та же таблица, что на лендинге — чтобы обещания не разошлись */}
      <PlansComparison lang={lang} user={user} onStart={handleCta} showHeading={false} />

      <Section title={t.limitsTitle}><Bullets items={t.limits} /></Section>
      <Section title={t.whyTitle}><p>{t.whyBody}</p></Section>

      {/* Блок для школ */}
      <div className="rounded-[28px] border-2 border-emerald-600/30 bg-emerald-50 dark:bg-emerald-950/30 p-7">
        <div className="flex items-center gap-3 mb-3">
          <School size={22} className="text-emerald-600 shrink-0" />
          <h2 className="text-lg sm:text-xl font-black uppercase tracking-tight">{t.schoolTitle}</h2>
        </div>
        <p className="text-slate-600 dark:text-zinc-300 leading-relaxed text-[15px] mb-5">{t.schoolBody}</p>
        <a
          href={`mailto:${CONTACT_EMAIL}`}
          className="inline-flex items-center gap-2 px-6 py-3 bg-white dark:bg-zinc-900 border-2 border-black dark:border-white rounded-xl font-black uppercase text-[11px] tracking-widest hover:bg-black hover:text-white dark:hover:bg-white dark:hover:text-black transition-all"
        >
          <Mail size={14} /> {t.schoolCta}
        </a>
      </div>

      <Section title={t.payTitle}><p>{t.payBody}</p></Section>
    </StaticPage>
  );
}
