import React from "react";
import { useNavigate } from "react-router-dom";
import { School, Mail } from "lucide-react";
import StaticPage, { Section, Bullets } from "../components/StaticPage";
import PlansComparison from "../components/PlansComparison";
import { CONTACT_EMAIL } from "../siteConfig";

const T = {
  RU: {
    title: "Тарифы",
    subtitle: "Бесплатно — 15 генераций в месяц. PRO — 150, за $25/мес. Ниже — что входит и где границы.",
    limitsTitle: "Честно о границах",
    limits: [
      "15 (PRO — 150) генераций в месяц считаются вместе для планов, тестов и отчётов и обнуляются 1-го числа.",
      "Сервис работает в браузере, офлайн-режима нет.",
      "Материалы генерирует языковая модель — их нужно проверять перед уроком.",
      "Мы можем ограничить нагрузку от одного аккаунта, если она мешает другим учителям.",
    ],
    whyTitle: "Почему это не автоматический чекаут",
    whyBody: "Сервис на ранней стадии, платёжный провайдер ещё не подключён. Переход на PRO — по письму: договариваемся об оплате и включаем PRO на вашем аккаунте вручную, обычно в течение дня.",
    schoolTitle: "Для школ и методобъединений",
    schoolBody: "Нужны аккаунты для всей школы, единый доступ для методиста или обучение коллектива? Напишите — обсудим отдельные условия.",
    schoolCta: "Написать нам",
    payTitle: "Что со сменой условий",
    payBody: "Изменения тарифов вступают в силу не раньше чем через 30 дней после уведомления. Контент, созданный до изменений, остаётся доступным и выгружаемым.",
  },
  KZ: {
    title: "Тарифтер",
    subtitle: "Тегін — айына 15 генерация. PRO — 150, $25/ай. Төменде — не кіретіні және шектеулері.",
    limitsTitle: "Шектеулер туралы шынымен",
    limits: [
      "Айына 15 (PRO — 150) генерация жоспар, тест және есеп үшін бірге есептеледі және айдың 1-інде нөлденеді.",
      "Сервис браузерде жұмыс істейді, офлайн режим жоқ.",
      "Материалдарды тілдік модель жасайды — сабақ алдында тексеру қажет.",
      "Бір аккаунттың жүктемесі басқа мұғалімдерге кедергі келтірсе, оны шектей аламыз.",
    ],
    whyTitle: "Неге бұл автоматты чекаут емес",
    whyBody: "Сервис ерте кезеңде, төлем провайдері әлі қосылған жоқ. PRO-ға өту хат арқылы: төлем туралы келісеміз де аккаунтыңызда PRO-ды қолмен қосамыз, әдетте бір күн ішінде.",
    schoolTitle: "Мектептер мен әдістемелік бірлестіктерге",
    schoolBody: "Бүкіл мектепке аккаунт, әдіскерге ортақ қолжетімділік немесе ұжымды оқыту керек пе? Жазыңыз — жеке шарттарды талқылайық.",
    schoolCta: "Бізге жазу",
    payTitle: "Шарттар өзгерсе",
    payBody: "Тариф өзгерістері хабарламадан кейін 30 күннен ерте күшіне енбейді. Өзгерістерге дейін жасалған мазмұн қолжетімді болып қалады және жүктеп алуға болады.",
  },
  EN: {
    title: "Pricing",
    subtitle: "Free — 15 generations a month. PRO — 150, for $25/mo. Here's what's included and where the limits are.",
    limitsTitle: "Honest about the limits",
    limits: [
      "The 15 (PRO: 150) monthly generations are counted together across plans, quizzes and reports, and reset on the 1st.",
      "The service runs in the browser; there is no offline mode.",
      "Materials are generated by a language model and need checking before the lesson.",
      "We may throttle a single account if its load affects other teachers.",
    ],
    whyTitle: "Why this isn't an automatic checkout",
    whyBody: "The service is early and a payment provider isn't connected yet. Moving to PRO is by email: we sort out payment and switch your account to PRO by hand, usually within a day.",
    schoolTitle: "For schools and departments",
    schoolBody: "Need accounts for a whole school, shared access for a head of department, or training for your staff? Email us — let's work out terms.",
    schoolCta: "Email us",
    payTitle: "If terms change",
    payBody: "Pricing changes take effect no sooner than 30 days after notice. Content created before a change stays accessible and exportable.",
  },
};

export default function PricingPage({ lang = "RU", user, setIsAuthOpen, setAuthMode, resetAuthFields, ...rest }) {
  const t = T[lang] || T.RU;
  const navigate = useNavigate();

  const handleCta = () => {
    if (user) { navigate("/hub"); return; }
    resetAuthFields?.();
    setAuthMode?.("signup");
    setIsAuthOpen?.(true);
  };

  return (
    <StaticPage
      lang={lang}
      user={user}
      isLanding={!user}
      setIsAuthOpen={setIsAuthOpen}
      setAuthMode={setAuthMode}
      resetAuthFields={resetAuthFields}
      {...rest}
      title={t.title}
      subtitle={t.subtitle}
    >
      {/* Одна и та же таблица, что на лендинге — чтобы обещания не разошлись */}
      <PlansComparison lang={lang} user={user} onStart={handleCta} showHeading={false} />

      <Section title={t.limitsTitle}><Bullets items={t.limits} /></Section>
      <Section title={t.whyTitle}><p>{t.whyBody}</p></Section>

      {/* Блок для школ */}
      <div className="rounded-[28px] border-2 border-emerald-600/30 bg-emerald-50 dark:bg-emerald-950/30 p-7">
        <div className="flex items-center gap-3 mb-3">
          <School size={22} className="text-emerald-600 shrink-0" />
          <h2 className="text-lg sm:text-xl font-black uppercase tracking-tight">{t.schoolTitle}</h2>
        </div>
        <p className="text-slate-600 dark:text-zinc-300 leading-relaxed text-[15px] mb-5">{t.schoolBody}</p>
        <a
          href={`mailto:${CONTACT_EMAIL}`}
          className="inline-flex items-center gap-2 px-6 py-3 bg-white dark:bg-zinc-900 border-2 border-black dark:border-white rounded-xl font-black uppercase text-[11px] tracking-widest hover:bg-black hover:text-white dark:hover:bg-white dark:hover:text-black transition-all"
        >
          <Mail size={14} /> {t.schoolCta}
        </a>
      </div>

      <Section title={t.payTitle}><p>{t.payBody}</p></Section>
    </StaticPage>
  );
}
