import React from "react";
import StaticPage, { Section, Bullets } from "../components/StaticPage";
import { CONTACT_EMAIL } from "../siteConfig";

const T = {
  RU: {
    title: "Условия использования",
    subtitle: "Правила, по которым работает Lesson Planner.",
    updated: "Обновлено: 12 августа 2026",
    s1: "Кто может пользоваться",
    s1body: "Сервис предназначен для учителей, учеников и родителей. Аккаунт создаётся на одного человека — не передавайте пароль коллегам. Ученики участвуют в тестах по коду доступа без регистрации.",
    s2: "Ваш контент — ваш",
    s2body: "Планы уроков, тесты и отчёты, которые вы создаёте, принадлежат вам. Вы можете свободно использовать их на уроках, распечатывать и выгружать в DOCX. Мы не публикуем ваш контент и не передаём его другим пользователям.",
    s3: "Проверяйте то, что сгенерировал ИИ",
    s3body: "Материалы создаёт языковая модель. Она может ошибаться в фактах, датах и формулировках. Ответственность за содержание урока остаётся на учителе — прочитайте план или тест перед тем, как нести его в класс.",
    s4: "Чего делать нельзя",
    s4items: [
      "Загружать чужие персональные данные без основания.",
      "Использовать сервис для создания оскорбительных или незаконных материалов.",
      "Автоматизировать массовые запросы к генерации и мешать работе сервиса.",
      "Пытаться получить доступ к чужим классам, тестам и результатам.",
    ],
    s5: "Доступность сервиса",
    s5body: "Сервис предоставляется «как есть». Мы стараемся, чтобы он работал без перебоев, но не гарантируем стопроцентную доступность: возможны технические работы и ограничения со стороны провайдера ИИ. Держите копию важных материалов (выгрузка в DOCX).",
    s6: "Стоимость",
    s6body: "Сейчас сервис бесплатен. Если появятся платные тарифы, действующие пользователи узнают об этом заранее, а уже созданный контент останется доступным.",
    s7: "Прекращение доступа",
    s7body: "Вы можете удалить аккаунт в любой момент, написав нам. Мы можем ограничить доступ, если аккаунт используется для нарушения этих условий.",
    s8: "Контакты",
    s8body: "Вопросы по условиям:",
  },
  KZ: {
    title: "Пайдалану шарттары",
    subtitle: "Lesson Planner жұмысының ережелері.",
    updated: "Жаңартылды: 2026 жылғы 12 тамыз",
    s1: "Кім пайдалана алады",
    s1body: "Сервис мұғалімдерге, оқушыларға және ата-аналарға арналған. Аккаунт бір адамға жасалады — құпия сөзді әріптестеріңізге бермеңіз. Оқушылар тестке код арқылы, тіркелусіз қатысады.",
    s2: "Сіздің мазмұныңыз — сіздікі",
    s2body: "Сіз жасаған сабақ жоспарлары, тесттер мен есептер сізге тиесілі. Оларды сабақта еркін пайдалануға, басып шығаруға және DOCX-ке жүктеуге болады. Біз сіздің мазмұныңызды жарияламаймыз және басқа пайдаланушыларға бермейміз.",
    s3: "ЖИ жасағанды тексеріңіз",
    s3body: "Материалдарды тілдік модель жасайды. Ол фактілерде, күндерде және тұжырымдарда қателесуі мүмкін. Сабақ мазмұнына жауапкершілік мұғалімде қалады — жоспарды немесе тестті сыныпқа апармас бұрын оқып шығыңыз.",
    s4: "Не істеуге болмайды",
    s4items: [
      "Негізсіз түрде бөгде адамдардың дербес деректерін жүктеу.",
      "Сервисті қорлайтын немесе заңсыз материалдар жасау үшін пайдалану.",
      "Генерацияға жаппай сұраныстарды автоматтандыру және сервистің жұмысына кедергі келтіру.",
      "Басқалардың сыныптарына, тесттеріне және нәтижелеріне қол жеткізуге тырысу.",
    ],
    s5: "Сервистің қолжетімділігі",
    s5body: "Сервис «қалай бар, солай» ұсынылады. Біз үзіліссіз жұмысқа тырысамыз, бірақ жүз пайыз қолжетімділікке кепілдік бермейміз: техникалық жұмыстар және ЖИ провайдері тарапынан шектеулер болуы мүмкін. Маңызды материалдардың көшірмесін сақтаңыз (DOCX-ке жүктеу).",
    s6: "Құны",
    s6body: "Қазір сервис тегін. Ақылы тарифтер пайда болса, қолданыстағы пайдаланушылар бұл туралы алдын ала біледі, ал жасалған мазмұн қолжетімді болып қалады.",
    s7: "Қолжетімділікті тоқтату",
    s7body: "Аккаунтты кез келген уақытта бізге жазу арқылы жоя аласыз. Аккаунт осы шарттарды бұзу үшін пайдаланылса, біз қолжетімділікті шектей аламыз.",
    s8: "Байланыс",
    s8body: "Шарттар бойынша сұрақтар:",
  },
  EN: {
    title: "Terms of Use",
    subtitle: "The rules Lesson Planner runs on.",
    updated: "Updated: 12 August 2026",
    s1: "Who can use it",
    s1body: "The service is for teachers, students and parents. An account belongs to one person — don't share your password with colleagues. Students join quizzes with an access code and no registration.",
    s2: "Your content is yours",
    s2body: "The lesson plans, quizzes and reports you create belong to you. Use them in class, print them, export them to DOCX. We don't publish your content or share it with other users.",
    s3: "Check what the AI produced",
    s3body: "Materials are generated by a language model. It can get facts, dates and wording wrong. Responsibility for what happens in the lesson stays with the teacher — read the plan or quiz before you take it into the classroom.",
    s4: "What you may not do",
    s4items: [
      "Upload other people's personal data without a lawful basis.",
      "Use the service to create abusive or illegal material.",
      "Automate bulk generation requests or otherwise disrupt the service.",
      "Attempt to access classes, quizzes or results that are not yours.",
    ],
    s5: "Availability",
    s5body: "The service is provided \"as is\". We work to keep it running, but we can't guarantee 100% uptime: maintenance happens and the AI provider can impose limits. Keep a copy of anything important (export to DOCX).",
    s6: "Cost",
    s6body: "The service is currently free. If paid plans appear, existing users will hear about it in advance and content you already created will stay accessible.",
    s7: "Ending access",
    s7body: "You can delete your account at any time by emailing us. We may restrict access if an account is used to break these terms.",
    s8: "Contact",
    s8body: "Questions about these terms:",
  },
};

export default function TermsPage({ lang = "RU", ...rest }) {
  const t = T[lang] || T.RU;

  return (
    <StaticPage lang={lang} {...rest} title={t.title} subtitle={t.subtitle} updated={t.updated}>
      <Section title={t.s1}><p>{t.s1body}</p></Section>
      <Section title={t.s2}><p>{t.s2body}</p></Section>
      <Section title={t.s3}><p>{t.s3body}</p></Section>
      <Section title={t.s4}><Bullets items={t.s4items} /></Section>
      <Section title={t.s5}><p>{t.s5body}</p></Section>
      <Section title={t.s6}><p>{t.s6body}</p></Section>
      <Section title={t.s7}><p>{t.s7body}</p></Section>
      <Section title={t.s8}>
        <p>
          {t.s8body}{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="font-black text-emerald-600 hover:underline">{CONTACT_EMAIL}</a>
        </p>
      </Section>
    </StaticPage>
  );
}
